### ISSUE TITLE
Add installation scripts

### ISSUE THREAD

**Issue by gabrielepanda** [ProgrammaBol/slither#4]

**Comment by faffa82** [comment]
I'm working on dependencies installation script (Python, setuptools, wxPython and jinja) for Windows. For now, I haven't find a way to install Python and wxPython without using interactive windowed installers.
If I have time, I'll also set up the Linux one.

**Comment by gabrielepanda** [comment]
If you're not able to add or test the linux setup, change the issue title to be related only to windows, and add another issue to generalize what you've done for linux.

**Comment by faffa82** [comment]
Added scripts for Windows and Linux Debian (Ubuntu). I'm unable to test a script for Mac OSX so I'll open a new issue for this purpose
