### ISSUE TITLE
Console: remove info tabs

### ISSUE THREAD

**Issue by gabrielepanda** [ProgrammaBol/slither#6]

**Comment by eineki** [comment]
As reported in [wxPython documentation](https://wxpython.org/Phoenix/docs/html/wx.py.html) the library offers several flavour of python console to choose from.
- wx.py.crust.Crust
- wx.py.shell.Shell
- wx.py.sliceshell.SlicesShell

As in docs, the Crust object create a splitted window with a Python console and additional controls in a tabbed view.

Using the wx.py.shell.Shell object solve the issue.
